<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <title>Inicio</title>
    <link rel="icon" href="./img/Logo.ico" type="image/x-icon"/>
    <link rel="stylesheet" href="./css/generic.css">
    <link rel="stylesheet" href="./css/header.css">
    <link rel="stylesheet" href="./css/dashboard.css">
</head>
<body>
holaaaaaaaaaaaaaaaaaaaaaaaa
</body>
</html>